name: Contao
main: de.minestar.contao.core.ContaoCore
version: ${pom.version}
softdepend: [Illuminati]
depend: [GroupManager, MinestarCore, MineStarLibrary]
commands:
    user:
    who:
    list:
    online:
    stats:
    contao: